"""First Migration

Revision ID: c395a6364ba1
Revises: 
Create Date: 2025-02-08 11:37:05.736452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c395a6364ba1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('QuestId', sa.String(length=36), nullable=False),
    sa.Column('Title', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.Column('Reward', sa.Integer(), nullable=False),
    sa.Column('Image', sa.Text(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('QuestId')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('PublicAddress', sa.String(length=100), nullable=False),
    sa.Column('ReferralCode', sa.String(length=6), nullable=True),
    sa.Column('RefferedBy', sa.String(length=36), nullable=True),
    sa.Column('TotalReferrals', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ReferralCode'),
    sa.UniqueConstraint('UserId')
    )
    op.create_index(op.f('ix_users_PublicAddress'), 'users', ['PublicAddress'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.String(length=36), nullable=False),
    sa.Column('QuestId', sa.String(length=36), nullable=False),
    sa.Column('MintCount', sa.Integer(), nullable=False),
    sa.Column('PointsEarned', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['QuestId'], ['quests.QuestId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UserId'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_points_id'), 'activity_points', ['id'], unique=False)
    op.create_table('referral_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Referer', sa.String(length=36), nullable=False),
    sa.Column('Referee', sa.String(length=36), nullable=False),
    sa.Column('PointsEarned', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Referee'], ['users.UserId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['Referer'], ['users.UserId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_points_id'), 'referral_points', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_points_id'), table_name='referral_points')
    op.drop_table('referral_points')
    op.drop_index(op.f('ix_activity_points_id'), table_name='activity_points')
    op.drop_table('activity_points')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_PublicAddress'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('quests')
    # ### end Alembic commands ###
