"""Second migration

Revision ID: dd81d1ee6a07
Revises: c395a6364ba1
Create Date: 2025-02-10 21:35:11.513347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd81d1ee6a07'
down_revision: Union[str, None] = 'c395a6364ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'is_deleted')
    # ### end Alembic commands ###
